- name: Deploy App using Ansible
  hosts: local
  become: true
  become_method: sudo

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy application files to Nginx directory
      copy:
        src: "{{ playbook_dir }}/../app/"
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
