<build>
    <finalName>JSPApp</finalName>

    <plugins>
        <plugin>
            <artifactId>maven-war-plugin</artifactId>
            <version>3.5.1</version>
            <configuration>
                <failOnMissingWebXml>false</failOnMissingWebXml>
            </configuration>
        </plugin>
    </plugins>

</build>
